
# Local Database
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: 5

default: &default
  adapter: postgis
  username: <%= ENV['rds_username'] %>
  password: <%= ENV['rds_password'] %>
  host: <%= ENV['rds_host'] %>

development:
  <<: *default
  database: devchallenge_development

test:
  <<: *default
  database: devchallenge_test

production:
  <<: *default
  database: devchallenge_production
